In [1]:
from selenium import webdriver 
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as ec
from selenium.webdriver.support.ui import WebDriverWait
from bs4 import BeautifulSoup as bs
import pandas as pd
import time

In [2]:
driver = webdriver.Firefox()

In [3]:
driver.get('https://eg.indeed.com/')

In [4]:
WebDriverWait(driver, 50).until(ec.presence_of_element_located((By.XPATH, '//*[@id="text-input-what"]')))

In [5]:
search = driver.find_element("xpath",'//*[@id="text-input-what"]')
search.send_keys('data analyst')
search.send_keys(Keys.ENTER)

In [6]:
df = pd.DataFrame({'job':[''],'company name':[''], 'date':[''], 'job type':[''], 'salary':[''], 'link':['']}, index = ['job'])
df = df.head(0)

In [7]:
time.sleep(5)

In [8]:
while True:
    time.sleep(2)
    soup = bs(driver.page_source, 'lxml')
    posts = soup.find_all('div', class_ = 'slider_container css-g7s71f eu4oa1w0')
    for post in posts:
        job = post.find('a', class_ = 'jcs-JobTitle css-jspxzf eu4oa1w0').text
        link = 'https://eg.indeed.com' + post.find('a', class_ = 'jcs-JobTitle css-jspxzf eu4oa1w0').get('href')
        date = post.find('span', class_ = 'date').text
        if 'Posted' in date:
            date = date[6:]
        if 'Posted' in date:
            date = date[6:]
        try :
            companyname = post.find('span', class_ = 'companyName').text
        except:
            companyname = 'unknown'
        s = post.find_all('div', class_ = 'attribute_snippet')
        if len(s) == 2:
            job_type = s[1].text
            Salary = s[0].text
        elif len(s) == 1:
            job_type = s[0].text
            Salary = 'unknown'
        else :
            jop_type = 'unknown'
            Salary = 'unknown'
        row = [job, companyname, date, job_type, Salary, link]
        lent = len(df)
        df.loc[lent] = row
    try :
        try:
            next_page = soup.find('a', {'aria-label' : 'Next Page'}).get('href')
        except:
            next_page = soup.find('a', {'aria-label' : 'Next'}).get('href')
    except:
        break
    next_page = 'https://eg.indeed.com' + next_page
    driver.get(next_page)

In [9]:
df.to_csv('indeed.csv', index= False)

In [10]:
df

,job,company name,date,job type,salary,link
0,Junior Collection Analyst,MaxAB,EmployerActive 3 days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=a903e6a7f9beaa...
1,Data Analyst Intern,IACC,30+ days ago,Internship,unknown,https://eg.indeed.com/rc/clk?jk=23389da6188d01...
2,Data Analyst,Brightskies,30+ days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=eff764fc144a21...
3,Data Analyst,Marketeers,30+ days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=c31e50444aee5b...
4,Senior Data Analyst,MaxAB,EmployerActive 8 days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=f2cb5b9c6f6f9c...
...,...,...,...,...,...,...
197,Senior Principal OIC/SOA Integration Consultan...,Oracle,30+ days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=4c31274b7011fe...
198,Snr C# Full Stack Developer,NJ PLACEMENT CONSULTING,30+ days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=a3acf106ee7642...
199,Manager - Transfer Pricing - International Tax...,EY,30+ days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=0e8fcd6336e7a1...
200,Senior SCM Techno-Functional Consultant - Tech...,Oracle,30+ days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=01bebdf3b5f937...
201,Senior Manager - Transfer Pricing - Internatio...,EY,30+ days ago,Full-time,unknown,https://eg.indeed.com/rc/clk?jk=43ac338d7ff74a...